# Sphere function
---
Description:

- Optimization (min)
- Single-objective
- Constraints (no)
---

The general equation is given by:

- $f(\mathbf{x}) = \sum_{i=1}^{M} x^2_i$, with  $-\infty \le x_i \le +\infty$,

and global minimum found at:

- $f(x_1, x_2, ..., x_M) = f(0, 0, ..., 0) = 0$.

### First we import python libraries and set up the directory of our code.

In [1]:
import os, sys
import numpy as np
from math import fsum, isclose
import cProfile, pstats

PROJECT_DIR = os.path.abspath('..')
sys.path.append(PROJECT_DIR)

### Here we import all our custom GA code.

In [2]:
# Import main classes.
from ppso.auxiliary.swarm import Swarm
from ppso.auxiliary.particle import Particle

from ppso.engines.binary_pso import BinaryPSO
from ppso.engines.standard_pso import StandardPSO
from ppso.engines.accelerated_pso import AcceleratedPSO

### Define the sphere function

In [3]:
# Sphere function.
def fun_Sphere(x: np.typing.ArrayLike, f_min: bool = True):
    
    # Compute the shpere function.
    f_val = np.sum(x**2)

    # Condition for termination.
    solution_found = isclose(f_val, 0.0, rel_tol=1.0e-6)

    # Assign the fitness value (check for minimization).
    fit_value = -f_val if f_min else f_val
    
    # Return the solution tuple.
    return fit_value, solution_found
# _end_def_

Here we set the PSO parameters.

In [4]:
# Random number generator.
rng = np.random.default_rng()

# Define the number of optimizing variables.
D = 5

# Define the number of particles.
N = 100

# Sample the initial points randomly.
X_t0 = rng.uniform(-100.0, +100.0, size=(N, D))

# Initial population.
swarm_t0 = Swarm([Particle(x) for x in X_t0])

# Create the StandardPSO object that will carry on the optimization.
'''
test_PSO = StandardPSO(initial_swarm= swarm_t0,
                       obj_func= fun_Sphere,
                       lower_bound= -100.0*np.ones(D),
                       upper_bound= +100.0*np.ones(D))

test_PSO = AcceleratedPSO(initial_swarm= swarm_t0,
                          obj_func= fun_Sphere,
                          lower_bound= -100.0*np.ones(D),
                          upper_bound= +100.0*np.ones(D))
'''
test_PSO = BinaryPSO(initial_swarm= swarm_t0,
                     obj_func= fun_Sphere,
                     lower_bound= -100.0*np.ones(D),
                     upper_bound= +100.0*np.ones(D))

### Optimization process.

Here we call the PSO object.

In [5]:
# cProfile.run('test_GA(epochs=1000, f_tol=1.0e-8, elitism=True, adapt_probs=True)', 'output.prof')

test_PSO.run(max_it = 1000,
             f_tol = 1.0e-5,
             options = {"w": 0.35, "c1": 0.65, "c2": 0.65},
             parallel=False,
             reset_swarm = True,
             verbose = True)

Initial f_optimal = 0.0000
[1 0 1 1 1]
[0 1 1 1 1]
[1 1 1 0 1]
[0 0 0 0 1]
[1 0 0 1 1]
[0 1 0 0 0]
[1 1 1 0 0]
[1 1 0 0 1]
[0 0 1 0 0]
[1 1 0 0 0]
[1 0 1 0 1]
[0 0 0 1 0]
[1 0 1 0 0]
[0 0 0 0 0]
[0 1 1 0 0]
[1 1 1 1 1]
[0 1 1 1 0]
[0 1 0 1 1]
[0 0 0 1 1]
[1 1 1 0 1]
[0 0 1 0 1]
[0 1 0 0 0]
[1 0 1 1 0]
[1 0 0 0 0]
[1 0 1 1 1]
[0 0 0 0 0]
[0 1 0 0 1]
[0 0 1 0 0]
[0 1 0 0 1]
[1 1 1 0 0]
[1 0 1 1 1]
[0 0 1 0 0]
[0 0 0 1 1]
[1 0 1 1 0]
[1 0 0 1 0]
[1 1 1 1 1]
[1 0 1 1 0]
[0 1 0 0 0]
[0 0 0 1 1]
[1 0 1 1 0]
[0 1 1 0 1]
[0 0 0 1 1]
[0 0 1 0 0]
[0 0 0 1 0]
[0 0 1 0 1]
[0 0 1 1 0]
[0 1 1 0 0]
[0 1 0 1 1]
[0 1 0 1 0]
[1 0 1 1 1]
[1 1 0 0 1]
[0 1 0 0 1]
[1 1 0 0 1]
[1 1 0 1 1]
[0 1 1 1 0]
[0 1 0 1 0]
[1 1 1 1 0]
[1 0 1 1 1]
[1 0 0 1 1]
[1 1 1 0 0]
[1 0 0 0 0]
[1 0 0 0 0]
[0 1 1 0 0]
[1 0 0 0 0]
[0 0 0 0 0]
[0 1 0 1 1]
[1 0 0 1 0]
[0 0 1 0 0]
[1 0 0 0 1]
[1 0 1 0 1]
[0 1 1 1 1]
[1 1 1 1 0]
[1 1 0 0 0]
[0 0 0 1 1]
[1 1 1 0 0]
[1 1 0 0 0]
[0 1 0 0 0]
[0 0 1 0 0]
[0 1 1 1 0]
[1 0 0 0 0]
[1 0 1 1 1]
[

In [6]:
# Extract the optimal solution from the PSO.
optimal_solution = test_PSO.swarm.best_particle()

# Display the (final) optimal value.
print(f"Minimum Found: {optimal_solution.value:.6f}\n")

# Display each gene value separately.
for i, xi in enumerate(optimal_solution.position, start=1):
    print(f"x{i} = {xi:>10.6f}")
# _end_for_

# True minimum: f(0.0, 0.0, ..., 0.0) = 0.0

Minimum Found: 0.000000

x1 =   0.000000
x2 =   0.000000
x3 =   0.000000
x4 =   0.000000
x5 =   0.000000


In [7]:
# p = pstats.Stats('output.prof')

In [8]:
# p.sort_stats('cumtime').print_stats(20)

### End of file

In [9]:
velocity = np.random.randn(10, 4)

1.0 / (1.0 + np.exp(-velocity))

array([[0.84859722, 0.82087   , 0.77309967, 0.71584031],
       [0.17601783, 0.7996573 , 0.29376731, 0.60818045],
       [0.10910897, 0.42962185, 0.68216622, 0.7302856 ],
       [0.36894344, 0.41402323, 0.37854766, 0.3662007 ],
       [0.54849661, 0.42888468, 0.71809229, 0.41042904],
       [0.21285609, 0.61983384, 0.60250372, 0.35237602],
       [0.39909416, 0.25414087, 0.4415114 , 0.69552602],
       [0.3974207 , 0.74655307, 0.29997909, 0.33190738],
       [0.20735063, 0.34788457, 0.5525352 , 0.61453344],
       [0.54339977, 0.49513899, 0.18784265, 0.67713961]])